version: 2
references:
  yarn_cache_key: &yarn_cache_key yarn-v1-{{ checksum "yarn.lock" }}
jobs:
  build:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - *yarn_cache_key
            - yarn-v1-
      - run:
          name: dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: lint
          command: yarn lint
      - run:
          name: config
          command: cp .env.example .env
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: migrate
          command: yarn db:migrate
      - run:
          name: deploy
          command: git push heroku master
      - save_cache:
          key: *yarn_cache_key
          paths: ~/circleci/node_modules
